devise:
  mailer:
    sender: "..."
app:
  host: "..."
  name: "..."
  mail:
    address: "..."
    port: 587
    domain: "..."
    user_name: "..."
    password: "..."
    authentication: "plain"
    enable_starttls_auto: true
  omniauth:
    host: "..."
    twitter:
      key: "..."
      secret: "..."
    google:
      key: "..."
      secret: "..."
    facebook:
      key: "..."
      secret: "..."
    github:
      key: "..."
      secret: "..."
    foursquare:
      key: "..."
      secret: "..."
redis:
  host: "..."
  port: "..."
  namespace: "..."